version: '3.8'

services:
  nEXT:
    restart: unless-stopped
    image: atproject/limitednext:lastest
    container_name: limitednext
    build:
      context: .
      dockerfile: ./Dockerfile
    #network_mode: host                                # Uncomment if using external DB
    links:
      - postgres                                       # Comment if using external DB
      - lavalink
    depends_on:
      - postgres
      - lavalink
    command: python atlb
    env_file: docker.env

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:3
    container_name: lavalink
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx6G
      - SERVER_PORT=2333
      - LAVALINK_SERVER_PASSWORD=youshallnotpass
    expose:
      - 2333
    ports:
      - "2333:2333"

  # Comment postgres if using external DB
  postgres:
    image: postgres:latest

    environment:
      POSTGRES_DB: "nextmdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "yourpassword"
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/0_init.sql